"""Deterministic seed data for the logistics demo.

All names and identifiers are fictional. The scenario is intentionally fixed so a
sales/demo flow is repeatable. Times are ISO-8601 with explicit offsets.
"""

from __future__ import annotations

from copy import deepcopy

DEMO_NOW = "2026-09-08T09:15:00-03:00"

CUSTOMERS = {
    "CUS-ATL-001": {
        "customer_id": "CUS-ATL-001",
        "name": "Atlas Medical Supplies Brasil",
        "segment": "enterprise",
        "tier": "platinum",
        "industry": "medical supplies",
        "primary_contact": {
            "name": "Marina Costa",
            "role": "Supply Chain Manager",
            "email": "marina.costa@example.invalid",
        },
        "notification_preferences": ["email", "sms"],
        "sla_profile": "healthcare-priority",
        "notes": "Time-sensitive replenishment. Proactive notification required for projected SLA breach > 60 minutes.",
    },
    "CUS-LUM-002": {
        "customer_id": "CUS-LUM-002",
        "name": "Lumina Electronics Brasil",
        "segment": "enterprise",
        "tier": "gold",
        "industry": "electronics",
        "primary_contact": {
            "name": "Rafael Mendes",
            "role": "Distribution Operations Lead",
            "email": "rafael.mendes@example.invalid",
        },
        "notification_preferences": ["email"],
        "sla_profile": "priority-b2b",
        "notes": "High-value electronics. Signature required at destination.",
    },
    "CUS-VER-003": {
        "customer_id": "CUS-VER-003",
        "name": "VerdeMart Retail",
        "segment": "enterprise",
        "tier": "silver",
        "industry": "retail",
        "primary_contact": {
            "name": "Paula Nogueira",
            "role": "Inbound Logistics Coordinator",
            "email": "paula.nogueira@example.invalid",
        },
        "notification_preferences": ["email"],
        "sla_profile": "economy-b2b",
        "notes": "Store replenishment freight. Consolidation is allowed when SLA remains protected.",
    },
    "CUS-NOV-004": {
        "customer_id": "CUS-NOV-004",
        "name": "NovaCasa Home & Living",
        "segment": "mid-market",
        "tier": "silver",
        "industry": "consumer goods",
        "primary_contact": {
            "name": "Thiago Lima",
            "role": "Logistics Analyst",
            "email": "thiago.lima@example.invalid",
        },
        "notification_preferences": ["email"],
        "sla_profile": "standard-b2b",
        "notes": "Standard domestic distribution account.",
    },
}

ORDERS = {
    "ORD-ATL-1007": {
        "order_id": "ORD-ATL-1007",
        "customer_id": "CUS-ATL-001",
        "customer_po": "PO-ATLAS-88421",
        "status": "in_transit",
        "created_at": "2026-09-07T13:40:00-03:00",
        "service_level": "Priority Air",
        "origin": {"city": "Campinas", "state": "SP", "country": "BR"},
        "destination": {"city": "Recife", "state": "PE", "country": "BR"},
        "promised_delivery": "2026-09-08T18:00:00-03:00",
        "contents": "Point-of-care diagnostic analyzers",
        "pieces": 6,
        "weight_kg": 84.0,
        "declared_value_brl": 186000.00,
        "business_criticality": "critical",
        "shipment_ids": ["BRX-784512"],
    },
    "ORD-LUM-2041": {
        "order_id": "ORD-LUM-2041",
        "customer_id": "CUS-LUM-002",
        "customer_po": "PO-LUM-20260907-41",
        "status": "in_transit",
        "created_at": "2026-09-07T16:10:00-03:00",
        "service_level": "Priority Air",
        "origin": {"city": "Guarulhos", "state": "SP", "country": "BR"},
        "destination": {"city": "Salvador", "state": "BA", "country": "BR"},
        "promised_delivery": "2026-09-09T10:00:00-03:00",
        "contents": "Enterprise network switches",
        "pieces": 12,
        "weight_kg": 190.0,
        "declared_value_brl": 310000.00,
        "business_criticality": "high",
        "shipment_ids": ["BRX-784533"],
    },
    "ORD-VER-3308": {
        "order_id": "ORD-VER-3308",
        "customer_id": "CUS-VER-003",
        "customer_po": "PO-VERDE-3308",
        "status": "in_transit",
        "created_at": "2026-09-07T10:20:00-03:00",
        "service_level": "Economy Air",
        "origin": {"city": "São Paulo", "state": "SP", "country": "BR"},
        "destination": {"city": "Brasília", "state": "DF", "country": "BR"},
        "promised_delivery": "2026-09-10T17:00:00-03:00",
        "contents": "Retail point-of-sale peripherals",
        "pieces": 22,
        "weight_kg": 420.0,
        "declared_value_brl": 92000.00,
        "business_criticality": "normal",
        "shipment_ids": ["BRX-784540"],
    },
    "ORD-NOV-4102": {
        "order_id": "ORD-NOV-4102",
        "customer_id": "CUS-NOV-004",
        "customer_po": "PO-NOVA-4102",
        "status": "out_for_delivery",
        "created_at": "2026-09-06T11:00:00-03:00",
        "service_level": "Standard Road",
        "origin": {"city": "Curitiba", "state": "PR", "country": "BR"},
        "destination": {"city": "Porto Alegre", "state": "RS", "country": "BR"},
        "promised_delivery": "2026-09-08T16:00:00-03:00",
        "contents": "Home organization products",
        "pieces": 14,
        "weight_kg": 160.0,
        "declared_value_brl": 28000.00,
        "business_criticality": "normal",
        "shipment_ids": ["BRX-784566"],
    },
}

SHIPMENTS = {
    "BRX-784512": {
        "tracking_number": "BRX-784512",
        "order_id": "ORD-ATL-1007",
        "customer_id": "CUS-ATL-001",
        "status": "exception",
        "substatus": "air_capacity_disruption",
        "service_level": "Priority Air",
        "mode": "air",
        "carrier": "TransNova Air Network",
        "origin_facility": "VCP-GTW",
        "current_facility": "GRU-GTW",
        "destination_facility": "REC-HUB",
        "current_location": "Guarulhos Air Gateway, SP",
        "planned_route": ["VCP-GTW", "GRU-GTW", "REC-HUB", "REC-LASTMILE"],
        "promised_delivery": "2026-09-08T18:00:00-03:00",
        "estimated_delivery": "2026-09-09T09:30:00-03:00",
        "exception_code": "WX_CAPACITY_ROLLOVER",
        "exception_description": "Severe convective weather at GRU reduced ramp capacity and the booked cargo movement was rolled to a later departure.",
        "disruption_id": "DISR-GRU-0908",
        "pieces": 6,
        "weight_kg": 84.0,
        "cargo_profile": "medical-device / ambient",
        "priority": "critical",
        "last_event_at": "2026-09-08T08:42:00-03:00",
        "recovery_status": "not_started",
        "selected_recovery_option": None,
    },
    "BRX-784533": {
        "tracking_number": "BRX-784533",
        "order_id": "ORD-LUM-2041",
        "customer_id": "CUS-LUM-002",
        "status": "exception",
        "substatus": "air_capacity_disruption",
        "service_level": "Priority Air",
        "mode": "air",
        "carrier": "TransNova Air Network",
        "origin_facility": "GRU-GTW",
        "current_facility": "GRU-GTW",
        "destination_facility": "SSA-HUB",
        "current_location": "Guarulhos Air Gateway, SP",
        "planned_route": ["GRU-GTW", "SSA-HUB", "SSA-LASTMILE"],
        "promised_delivery": "2026-09-09T10:00:00-03:00",
        "estimated_delivery": "2026-09-09T13:15:00-03:00",
        "exception_code": "WX_CAPACITY_ROLLOVER",
        "exception_description": "The booked GRU-SSA movement was cancelled during the weather capacity reduction.",
        "disruption_id": "DISR-GRU-0908",
        "pieces": 12,
        "weight_kg": 190.0,
        "cargo_profile": "high-value electronics",
        "priority": "high",
        "last_event_at": "2026-09-08T08:55:00-03:00",
        "recovery_status": "not_started",
        "selected_recovery_option": None,
    },
    "BRX-784540": {
        "tracking_number": "BRX-784540",
        "order_id": "ORD-VER-3308",
        "customer_id": "CUS-VER-003",
        "status": "exception",
        "substatus": "air_capacity_disruption",
        "service_level": "Economy Air",
        "mode": "air",
        "carrier": "TransNova Air Network",
        "origin_facility": "GRU-GTW",
        "current_facility": "GRU-GTW",
        "destination_facility": "BSB-HUB",
        "current_location": "Guarulhos Air Gateway, SP",
        "planned_route": ["GRU-GTW", "BSB-HUB", "BSB-LASTMILE"],
        "promised_delivery": "2026-09-10T17:00:00-03:00",
        "estimated_delivery": "2026-09-10T13:30:00-03:00",
        "exception_code": "WX_CAPACITY_ROLLOVER",
        "exception_description": "Economy freight was deferred to protect higher-priority freight during reduced ramp capacity.",
        "disruption_id": "DISR-GRU-0908",
        "pieces": 22,
        "weight_kg": 420.0,
        "cargo_profile": "general cargo",
        "priority": "normal",
        "last_event_at": "2026-09-08T09:02:00-03:00",
        "recovery_status": "not_started",
        "selected_recovery_option": None,
    },
    "BRX-784566": {
        "tracking_number": "BRX-784566",
        "order_id": "ORD-NOV-4102",
        "customer_id": "CUS-NOV-004",
        "status": "out_for_delivery",
        "substatus": "courier_route",
        "service_level": "Standard Road",
        "mode": "road",
        "carrier": "TransNova Road",
        "origin_facility": "CWB-HUB",
        "current_facility": "POA-LASTMILE",
        "destination_facility": "POA-LASTMILE",
        "current_location": "Porto Alegre, RS",
        "planned_route": ["CWB-HUB", "POA-HUB", "POA-LASTMILE"],
        "promised_delivery": "2026-09-08T16:00:00-03:00",
        "estimated_delivery": "2026-09-08T14:45:00-03:00",
        "exception_code": None,
        "exception_description": None,
        "disruption_id": None,
        "pieces": 14,
        "weight_kg": 160.0,
        "cargo_profile": "general cargo",
        "priority": "normal",
        "last_event_at": "2026-09-08T08:50:00-03:00",
        "recovery_status": "not_applicable",
        "selected_recovery_option": None,
    },
}

TRACKING_EVENTS = {
    "BRX-784512": [
        {"timestamp": "2026-09-07T15:12:00-03:00", "code": "PICKED_UP", "location": "Campinas, SP", "description": "Shipment collected from customer facility."},
        {"timestamp": "2026-09-07T17:05:00-03:00", "code": "RECEIVED_ORIGIN", "location": "VCP Air Gateway, SP", "description": "Shipment received and security screened."},
        {"timestamp": "2026-09-08T05:55:00-03:00", "code": "TRANSFERRED", "location": "GRU Air Gateway, SP", "description": "Shipment transferred to GRU for booked northbound air movement."},
        {"timestamp": "2026-09-08T08:42:00-03:00", "code": "EXCEPTION", "location": "GRU Air Gateway, SP", "description": "Booked movement rolled because severe weather reduced ramp and aircraft capacity."},
    ],
    "BRX-784533": [
        {"timestamp": "2026-09-07T18:22:00-03:00", "code": "RECEIVED_ORIGIN", "location": "GRU Air Gateway, SP", "description": "Shipment received and security screened."},
        {"timestamp": "2026-09-08T08:55:00-03:00", "code": "EXCEPTION", "location": "GRU Air Gateway, SP", "description": "GRU-SSA movement cancelled during weather disruption."},
    ],
    "BRX-784540": [
        {"timestamp": "2026-09-07T14:40:00-03:00", "code": "RECEIVED_ORIGIN", "location": "GRU Air Gateway, SP", "description": "Shipment received into economy network."},
        {"timestamp": "2026-09-08T09:02:00-03:00", "code": "EXCEPTION", "location": "GRU Air Gateway, SP", "description": "Economy shipment deferred during constrained capacity window."},
    ],
    "BRX-784566": [
        {"timestamp": "2026-09-07T06:30:00-03:00", "code": "DEPARTED_HUB", "location": "Curitiba, PR", "description": "Linehaul departed Curitiba."},
        {"timestamp": "2026-09-08T06:55:00-03:00", "code": "AT_DESTINATION", "location": "Porto Alegre, RS", "description": "Received at destination station."},
        {"timestamp": "2026-09-08T08:50:00-03:00", "code": "OUT_FOR_DELIVERY", "location": "Porto Alegre, RS", "description": "Loaded on delivery route POA-17."},
    ],
}

DISRUPTIONS = {
    "DISR-GRU-0908": {
        "disruption_id": "DISR-GRU-0908",
        "type": "weather_capacity",
        "facility": "GRU-GTW",
        "facility_name": "Guarulhos Air Gateway",
        "severity": "major",
        "status": "active",
        "started_at": "2026-09-08T07:35:00-03:00",
        "expected_recovery_at": "2026-09-08T14:00:00-03:00",
        "description": "Severe convective weather and ramp restrictions reduced cargo processing and available uplift at GRU.",
        "operational_note": "Priority allocation is active. Recovery capacity is available via VCP and selected CNF connections.",
        "impacted_shipments": ["BRX-784512", "BRX-784533", "BRX-784540"],
    }
}

RECOVERY_OPTIONS = {
    "BRX-784512": [
        {
            "option_id": "REC-ATL-VCP",
            "type": "reroute_air",
            "description": "Truck transfer GRU→VCP and protect space on VCP→REC priority flight.",
            "new_estimated_delivery": "2026-09-08T21:40:00-03:00",
            "incremental_cost_brl": 1850.00,
            "capacity_available": True,
            "operational_risk": "medium",
            "customer_impact": "Projected 3h40 SLA miss instead of 15h30.",
            "recommended": True,
        },
        {
            "option_id": "REC-ATL-WAIT",
            "type": "wait_next_planned",
            "description": "Keep at GRU and move on next protected GRU→REC departure after weather recovery.",
            "new_estimated_delivery": "2026-09-09T09:30:00-03:00",
            "incremental_cost_brl": 0.00,
            "capacity_available": True,
            "operational_risk": "low",
            "customer_impact": "Projected 15h30 SLA miss.",
            "recommended": False,
        },
    ],
    "BRX-784533": [
        {
            "option_id": "REC-LUM-CNF",
            "type": "reroute_air",
            "description": "Reroute GRU→CNF→SSA using partner capacity with protected connection.",
            "new_estimated_delivery": "2026-09-09T08:30:00-03:00",
            "incremental_cost_brl": 680.00,
            "capacity_available": True,
            "operational_risk": "medium",
            "customer_impact": "Protects current delivery commitment with 1h30 buffer.",
            "recommended": True,
        },
        {
            "option_id": "REC-LUM-WAIT",
            "type": "wait_next_planned",
            "description": "Wait for the next GRU→SSA movement after ramp restrictions ease.",
            "new_estimated_delivery": "2026-09-09T13:15:00-03:00",
            "incremental_cost_brl": 0.00,
            "capacity_available": True,
            "operational_risk": "low",
            "customer_impact": "Projected 3h15 SLA miss.",
            "recommended": False,
        },
    ],
    "BRX-784540": [
        {
            "option_id": "REC-VER-WAIT",
            "type": "wait_next_planned",
            "description": "Retain on next available economy GRU→BSB movement.",
            "new_estimated_delivery": "2026-09-10T13:30:00-03:00",
            "incremental_cost_brl": 0.00,
            "capacity_available": True,
            "operational_risk": "low",
            "customer_impact": "No projected SLA breach; 3h30 delivery buffer remains.",
            "recommended": True,
        },
        {
            "option_id": "REC-VER-ROAD",
            "type": "convert_to_road",
            "description": "Convert to expedited road linehaul GRU→BSB.",
            "new_estimated_delivery": "2026-09-10T09:00:00-03:00",
            "incremental_cost_brl": 920.00,
            "capacity_available": True,
            "operational_risk": "medium",
            "customer_impact": "Earlier delivery, but premium spend is not justified while SLA is protected.",
            "recommended": False,
        },
    ],
}

INCIDENTS = {
    "INC-9001": {
        "incident_id": "INC-9001",
        "tracking_number": "BRX-784512",
        "disruption_id": "DISR-GRU-0908",
        "type": "shipment_exception",
        "priority": "P1",
        "status": "open",
        "owner": "Brazil Air Control Tower",
        "created_at": "2026-09-08T08:50:00-03:00",
        "summary": "Atlas Medical priority shipment projected to miss delivery commitment because of GRU weather capacity disruption.",
        "next_action": "Evaluate protected VCP recovery and notify customer before 10:00 BRT.",
    }
}

CASES = {}
NOTIFICATIONS = []
RECOVERY_ACTIONS = []

FACILITIES = {
    "GRU-GTW": {"name": "Guarulhos Air Gateway", "city": "Guarulhos", "state": "SP", "type": "air_gateway"},
    "VCP-GTW": {"name": "Viracopos Air Gateway", "city": "Campinas", "state": "SP", "type": "air_gateway"},
    "REC-HUB": {"name": "Recife Distribution Hub", "city": "Recife", "state": "PE", "type": "hub"},
    "SSA-HUB": {"name": "Salvador Distribution Hub", "city": "Salvador", "state": "BA", "type": "hub"},
    "BSB-HUB": {"name": "Brasília Distribution Hub", "city": "Brasília", "state": "DF", "type": "hub"},
    "POA-LASTMILE": {"name": "Porto Alegre Delivery Station", "city": "Porto Alegre", "state": "RS", "type": "last_mile"},
}


def fresh_state() -> dict:
    """Return a deep copy of the deterministic demo database."""
    return deepcopy(
        {
            "customers": CUSTOMERS,
            "orders": ORDERS,
            "shipments": SHIPMENTS,
            "tracking_events": TRACKING_EVENTS,
            "disruptions": DISRUPTIONS,
            "recovery_options": RECOVERY_OPTIONS,
            "incidents": INCIDENTS,
            "cases": CASES,
            "notifications": NOTIFICATIONS,
            "recovery_actions": RECOVERY_ACTIONS,
            "facilities": FACILITIES,
        }
    )
